### PR TITLE
ran `eslint --fix` on all js files to fix tabs and semicolons

### PR DESCRIPTION
**Pull request by greggraf**
This pull request address "Consider turning on semi and indent ESLint rules" #240.

I updated the config in `.eslintrc.json` to turn on the rules for semicolons and indents, then ran the command `./node_modules/.bin/eslint --fix ./` to automatically fix any errors found.

It touched/fixed a large number of files and though it is a relatively simple change, it may impact the merge-worthiness of existing pull requests and branches.

### CODE REVIEW

**Review by oderby — COMMENTED** [review]
Let's wait for #229 #256 and #250 to merge first, then we can re-do this change and push it in then. But otherwise, the changes look fine to me.

**Comment by cdoremus** [comment]
I agree with @oderby that we should wait on this. I'm not sure how far along is #251 but we might want to wait for that one too.

**Comment by nickoneill** [comment]
I'd be happy to get these improved rules turned on now if you think the time is appropriate @cdoremus / @greggraf

**Comment by cdoremus** [comment]
I think I'd wait to use `eslint --fix` on our code until after #251 gets pushed to master since that PR involves a lot of changes.

**Comment by oderby** [comment]
just pushed up an update, so this is ready to go if we want.

**Comment by nickoneill** [comment]
👍 Will merge this tonight!

**Review by nickoneill — APPROVED** [review]

**Comment by nickoneill** [comment]
Consistency 😍

**Pull request merged**
