### PR TITLE
A proper not found page if people use a url that isn't routed

### PR DESCRIPTION
**Pull request by nickoneill**
This is better than serving the home page for every url, right?

Note: I combined the idea of a Container and Page into a single file for this since it's unlikely it grow very large.

### CODE REVIEW

**Comment by cdoremus** [comment]
@nickoneill  this is a good idea, but I think that `NotFound` should be called `NotFoundPage` to be consistent with the other pages (knowing that `NotFound` encapsulates a Page, Container and Component).

**Comment by nickoneill** [comment]
OK, that makes sense.

**Comment by nickoneill** [comment]
ok, all set!

**Review by cdoremus — APPROVED** [review]
Good to go!

**Pull request merged**
