### PR TITLE
Fix small bug where contactIndices were reset.

### PR DESCRIPTION
**Pull request by oderby**
If you loaded the "more issues" page, you'd lose your progress
on calls. This fixes that issue.

I missed this in reviewing #220.

### CODE REVIEW

**Comment by cdoremus** [comment]
@oderby we really need to refactor main.js as you suggested in #206 so we can unit tests changes like this (in addition to improve code organization). My main aim of creating an E2E test suite is to enable this kind of refactoring without the fear of breaking everything.

**Comment by oderby** [comment]
Yeah, I have a branch locally starting this work. Was waiting for e2e tests
to land.

**Comment by oderby** [comment]
@cdoremus are you proposing we block merging this bug fix until we have an e2e test, or would you be willing to approve this and accept an issue filed to add the e2e test later?

**Comment by cdoremus** [comment]
No, tests should not block approval of this PR. I'll review it later today.

**Review by cdoremus — APPROVED** [review]
Works as advertised! Please merge when you have a chance.

**Pull request merged**
