### PR TITLE
Set debug mode based on localStorage

### PR DESCRIPTION
**Pull request by phoebejaffe**
Addresses #157

To turn on debug mode, simply set the localStorage key to true in the console:
```
localStorage['org.5calls.debug'] = 'true'
```

### CODE REVIEW

**Comment by phoebejaffe** [comment]
Note that the couple of console.logs will disappear unless you turn on "debug mode" with the incantation above :)

**Comment by beausmith** [comment]
@benjaffe - I love this solution. 

I've been meaning to inquire as to if anyone is using these console messages… as I was going to "solve" this by removing these console.log lines.

My thinking is that these are only useful to someone who is debugging the geolocation code… and since that is not an ongoing effort they are no longer useful. If someone is debugging geolocation in the future they can add debugging in… and then remove it before they submit a PR.

Agree/Disagree. Thoughts?

**Comment by nickoneill** [comment]
Yeah, that's the right way to approach this @beausmith. These should never really be in prod in the first place. The debug framework is good though!

**Comment by phoebejaffe** [comment]
I agree that generally logging shouldn't be committed, but if it's innocuous, it's kinda nice to see it doing high-level things when debug mode is on. Makes it easier to trace, possibly generally debug.

So IMO, 'getting geoposition' and 'selecting issue abcdef' are okay, but `console.log('yo1');` isn't :)

**Pull request merged**
