### PR TITLE
Used warnings from eslint to clean up main.js

### PR DESCRIPTION
**Pull request by greggraf**
- used `const` or `let` where variables were undeclared
- removed unused variable references, 
- added comment to identify global vendor objects used in the file
- added call to done() in two 'effects' that should maybe just be plain functions

### CODE REVIEW

**Comment by cdoremus** [comment]
I think this PR should wait until #233 gets merged to master so the modifications can be checked against the updated ```.eslintrc.json```.

**Comment by cdoremus** [comment]
I have created #238 to track the cleanup of the eslint ```no-undef``` and ```no-unused-vars``` violations.

It is our usual practice to create a Github issue to allow discussion and tracking of changes before they are implemented in a PR.

**Comment by greggraf** [comment]
Thanks @cdoremus - so would the proper move be to reference this PR in the newly created issue once #233 has been merged (and I have verified it still works)?

**Comment by greggraf** [comment]
Just ran against the latest code and verified that this PR takes care of all the ESLint warnings in /static/js/main.js.

**Review by cdoremus — APPROVED** [review]
Checked OK against #233 changes with 'gulp eslint'. Cuts eslint violations from 117 to 39. Good work!

**Pull request merged**
