### PR TITLE
Globally apply es2040 for fuller browser support

### PR DESCRIPTION
**Pull request by greggraf**
This pull request addresses #239 - applying the ES2040 shim to lower dependencies (Choo was the culprit for the bug).

### CODE REVIEW

**Comment by nickoneill** [comment]
Looking through this and #239 - it's not clear if this is still the solution to provide IE 10 support? Can we enable saucelabs testing on IE10 to be clear what this is fixing?

Please advise, I don't have a problem running es2040 on everything if it makes shit work.

**Comment by greggraf** [comment]
I hope this clarifies and does not add to confusion (wincing smiley face)

1. IE 10 is already enabled for testing on SauceLabs
2. The error in question is:
```
SCRIPT1002: Syntax error 
app.js, line 1152 character 1
```
3. This error exhibits itself in IE10 on SauceLabs only on branches  where `main.js` is included in Karma testing (`main.js` is the only file that requires `choo`)
4. Visiting 5calls.org with IE10 also exhibits the error (visiting with Chrome on Windows does not throw an error)
5. I can replicate the error when running the app locally and using IE10 (Chrome on Windows does not throw an error)
6. For illustration: 

   This is a screenshot of the site using IE 10:
     https://www.webpagetest.org/result/170321_1C_MCW/1/screen_shot/
   
   This is a screenshot using Firefox:
      https://www.webpagetest.org/result/170321_Z3_ME8/1/screen_shot/

As best I can figure, the code in Choo.js uses `const` and ES2040 does not transpile dependencies in `node_modules` by default. It works in Chrome because `const` is supported, but in IE10 it is not.

This fix (branch) works in IE10 for me locally, but leads to further IE10 bugs (like `onload` not being supported) as I have started to list in #239

**Comment by nickoneill** [comment]
Replied specifically about IE 10 in #239. We can still apply es2040 globally via this PR if you think it's worth it with or without IE 10 support.

**Comment by oderby** [comment]
If I understand correctly, this will recursively apply the es2040 transform to all code pulled into our application via require statements? If so, I have a mostly theoretical/philosophical concern that this changes the upstream dependencies, such that the code we're using is not necessarily the code they've distributed, and could result in subtle bugs/issues/confusions in the future when comparing functionality observed on our site with expected behavior of the upstream dependencies.

Also, going one step further on what Nick said - is this the right thing to do, independent of IE 10 support? 

Nevertheless, I'm leaning in favor of this change, because I trust es2040 transform is idempotent (and so my first concern is purely hypothetical), and think the defensive wins (against future bugs like #239) is worth it, regardless of IE10 support or not.

**Comment by greggraf** [comment]
I agree about altering upstream dependencies. And its messy. What if an upstream dependency relies on an ES6 feature that ES2040 doesn't support.

For what its worth,  the approach of applying the transform globally is what is recommended here: https://github.com/yoshuawuyts/choo/blob/f84ec43fa58508cc20fe537d752a14901339f0cd/README.md#choo--internet-explorer--safari

I was thinking - absent applying ES2040 globally, why bother with the ES2040 at all? If the purpose of the plugin is to polyfill a subset of unevenly supported ES6 features, but dependencies are exempt what is it really doing?

But then, I think in the end, its safer to apply the transform to dependencies as an extra layer of compatibility guarantee.

**Comment by nickoneill** [comment]
First chance we'll get to try this out will probably be April 9, our JS error tracking resets and we'll be better able to measure the effect of this!

**Comment by oderby** [comment]
@nickoneill so are you proposing we defer taking further action on this PR until after April 9?

**Comment by nickoneill** [comment]
Yes, we'll be able to get a baseline error rate on the 9th, then we can make this change on the 10th or later and see how it changes the error rates.

**Comment by nickoneill** [comment]
I'm pretty happy with our baseline errors on Sentry (working on getting more people invited to check that out). What else has to happen to move forward with this @greggraf ?

**Comment by greggraf** [comment]
@nickoneill - Unless I am misunderstanding something, I think all that is needed to move forward is to merge this PR.

Does the error that IE throws show up currently in Sentry?
```
SCRIPT1002: Syntax error 
app.js, line 1152 character 1
```

**Comment by nickoneill** [comment]
I don't see it in sentry, but I can't even filter by IE 10, I wonder if sentry even supports that browser. Let's merge!

**Review by nickoneill — APPROVED** [review]

**Pull request merged**
