### PR TITLE
New FAQ page

### PR DESCRIPTION
**Pull request by nickoneill**
* New FAQ page, no more ugly zendesk page that no one went to
* Moved contact from footer to FAQ
* Removed Twitter from footer

### CODE REVIEW

**Comment by oderby** [comment]
This will need a corresponding change on the backend to expose the /faq route to be served the index.html, right?

**Comment by nickoneill** [comment]
Yep, maybe a good time to be more generous with those routes.

**Comment by oderby** [comment]
This will likely need some attention to fixup e2e tests for hte faq page

**Comment by nickoneill** [comment]
* needs changed e2e tests for footer as well

**Comment by nickoneill** [comment]
Faq incoming. Translation issue is already up.

**Pull request merged**
