### PR TITLE
Fix #185 - focus and select input when prompted for address.

### LINKED ISSUE #185: "set your location" or "add an address" prompts should clear and focus the input
Some feedback with confusion on these items. Clearing the input lets people see the placeholder where it says "address or zip"

### PR DESCRIPTION
**Pull request by oderby**
Adds a new effect 'focusLocation' to achieve this, called
from within issuesLocation component if appropriate.

TODO: how to write tests for this?

### CODE REVIEW

**Comment by oderby** [comment]
First, I'm not entirely sure this is the "choo" idiomatic way to achieve this - basically we want to modify the DOM immediately after it's rendered/updated. It seems like the best place for this logic is in an effect...but I'm open to other ideas? Couldn't really find any good examples of recommended ways to do this within Choo's docs.

Also, @Mr0grog @cdoremus I'd love to hear if you have any suggestions for ways to test this sort of thing. In general, the challenge is testing the effects of DOM manipulations carried out in model effects. This is probably not a simple unit test, as it's testing multiple parts of the app working in concert. Did either of you find any canonical examples/resources for testing Choo applications? All I've found was [this presentation](https://www.sitepoint.com/functional-programming-choo/), but it only talks about unit testing views/components or reducers.

**Comment by cdoremus** [comment]
I've put together some tests for your new issuesLocation code, but there is a lot of other logic in that component that you should test:
```
describe('issuesLocation component', () => {
  it('should call send("focusLocation") when askingLocation is true and ' +
    'fetchingLocation is false', () => {
    const expected = 'focusLocation';
    let actual = undefined;
    // mock impl to test that it is being called in component
    let send = (msg) => actual = msg;
    let state = {
      askingLocation: true,
      fetchingLocation: false
    };
    issuesLocation(state, null, send);
    expect(actual).to.equal(expected);
  });
  it('should NOT call send("focusLocation") when askingLocation is true and ' +
    'fetchingLocation is true', () => {
    const expected = 'focusLocation';
    let actual = undefined;
    let send = (msg) => actual = msg;
    let state = {
      askingLocation: true,
      fetchingLocation: true
    };
    issuesLocation(state, null, send);
    expect(actual).to.not.equal(expected);
  });
  it('should NOT call send("focusLocation") when askingLocation is false and ' +
    'fetchingLocation is false', () => {
    const expected = 'focusLocation';
    let actual = undefined;
    let send = (msg) => actual = msg;
    let state = {
      askingLocation: false,
      fetchingLocation: false
    };
    issuesLocation(state, null, send);
    expect(actual).to.not.equal(expected);
  });
});
```
The focusLocation effect in main.js cannot be tested unless the function is exported. Personally, I think that main.js is getting too long and complicated. I'd recommend that the state, reducers and effects be  refactored into separate files to allow easier testing and better code clarity.

**Comment by oderby** [comment]
@capndesign any further thoughts on this PR? (Asking because you requested to review.) I'm inclined to merge as is and track coding better tests in a separate issue.

**Comment by cdoremus** [comment]
As I stated above, the tests I provided covered a very small subset of the issuesLocation component logic. I would like an issue created to fill in the coverage gaps before this PR is merged into master. Testing is always better done close to the initial development of a new piece of code as possible. I've seen too much testing procrastination in my days as a dev (over 20 years) that ends up being wishful thinking. We've already derived value from our unit tests. This value will disproportionately increase as our code coverage increases.

**Comment by oderby** [comment]
Good point. I will try and get something up with better unit test coverage
for the issuesLocation component soon. Hopefully tonight.

**Comment by oderby** [comment]
@cdoremus @capndesign either of you up to review this? I think it's ready to merge otherwise...

**Comment by cdoremus** [comment]
@oderby, I'll do the review and try to get to it tonight

**Comment by cdoremus** [comment]
I guess that I do not have 'reviewer' status to do an official review, but I did take a look at the code, paying special attention to the tests, and see no reason why it cannot be merged into master. Good job!

**Comment by nickoneill** [comment]
Is there a "review changes" button if you swap to the files changes tab @cdoremus ?

**Review by capndesign — COMMENTED** [review]
Everything looks good in the diff and the code runs as expected. I’m having trouble getting the karma tests to run on this machine, but other than that things look good to me.

**Review by cdoremus — APPROVED** [review]
Code looks good. All tests pass. This branch is ready to merge to master. Good job!

**Comment by nickoneill** [comment]
👍

**Pull request merged**
