### PR TITLE
Improve documentation, setup steps

### PR DESCRIPTION
**Pull request by agjohnson**
Setup steps were lacking for the application server. I've added some information
that hopefully helps here. It didn't seem necessary to run a Python process to
server HTTP, so I included a gulp task for serving these files from Gulp. I'm
not sure what the production serving mechanism looks like however.

This also adds some convenience make targets for the setup steps. I'm not super
confident with Go however, so perhaps this introduces other problems.

### CODE REVIEW

**Comment by nickoneill** [comment]
Looks like you got scooped by #53 for the readme, but the other changes look great, can you trim it down to just those?

**Comment by agjohnson** [comment]
Oops, my bad. I'll get a rebase up shortly.

**Comment by agjohnson** [comment]
Rebase is pushed up now.

**Comment by nickoneill** [comment]
Good stuff @agjohnson! I'll get this pulled in shortly

**Review by nickoneill — APPROVED** [review]

**Pull request merged**
