### PR TITLE
typo - missing quote and slash on href value.

### PR DESCRIPTION
**Pull request by beausmith**
Introduced here: https://github.com/5calls/5calls/commit/6e4341390876c2936ac528bfd2b560655a9292db#diff-13f2f55f8c5ad0a842db049e9f8b0caaR27

cc @liamdanger

### CODE REVIEW

**Comment by oderby** [comment]
This is definitely related to #216 - the url I see when I go back is exactly of form `issue{issueid}"`... Will pull down and test in a second.

**Comment by nickoneill** [comment]
Ah, awesome. I looked around for this the other night in the JS functions for changing location, didn't even think to check the html itself.

**Review by oderby — APPROVED** [review]
lgtm

**Comment by oderby** [comment]
So this definitely alleviates the worst part of #216, but it still takes two back clicks to go back to the previous issue/page. So let's leave #216 open and use it to track fixing the rest of the issue.

**Comment by nickoneill** [comment]
OK, this solution got me thinking. The double-back issue is because we have a handleClick AND an anchor that are doing the same thing. So effectively we're following the same link twice every time we click on an issue and choo adds the browser history twice.

Now that we have testing, we can pick one or the other and test across browsers so make sure we're not breaking IE 10 (which I think might be the reason that anchor got there in the first place).

**Comment by oderby** [comment]
@nickoneill You're right that we only need one or the other. It seems to me the best option is to leave the anchor and just remove [main.js:L377](https://github.com/5calls/5calls/blob/master/static/js/main.js#L377). 

But I don't follow what you think we should be testing on IE10?

**Comment by nickoneill** [comment]
Just tapping on the issue and getting the detail screen to show up. IIRC, some versions of IE don't like onclicks on non-anchor elements? If the tests run OK I'm good, I'm literally pulling at information I learned about IE more than 6 years ago to hypothesize here.

**Comment by oderby** [comment]
Okay, will need to add that to the growing list of e2e tests to write once we get #209 up and running. For now, I'll push a fix for the double-back issue.

**Pull request merged**
