### PR TITLE
Noah frontpage testing

### PR DESCRIPTION
**Pull request by nabrahamson**
Currently a work in progress. Creating examples of e2e tests with TestCafe

### CODE REVIEW

**Comment by nickoneill** [comment]
Awesome, this looks pretty cool so far. Let's get a couple small tests running, then figure out how we can hook it to browserstack / github on commits.

Then we can follow-on with rounding out the test cases.

**Comment by nabrahamson** [comment]
Tests to be written:

- Tests that should be run for each endpoint
- [x] Full Page: All external assets are loaded (images, or other media)
- [x] Header: Home link is displayed and is functional
- [x] Header: Login dropdown is displayed and is functional when user is not logged in (Shows modal and modal has expected elements)
- [x] Header: Donation bar (Get Involved bar) is displayed and each link is functional
- [x] Header: User may sign in to account (This may need a dummy account accessable to the test runner)
- [x] Sidebar: Sidebar is displayed
- [x] Sidebar - Non Group: Sidebar contains location component and location may be changed
- [x] Sidebar - Non Group: Sidebar contains a list of 10 active issues ( Each issue may be clicked to direct to a call page with the appropriate call displayed)
- [x] Sidebar - Non Group: Sidebar footer is visiable and says "View all active issues". Clicking the link should navigate to the /more endpoint
- [x] Footer - Footer is displayed at the bottom of the page. 
- [x] Footer - Links on the left, middle, and right all navigate to the correct webpages
- [x] Footer - Disclaimer is displayed properly in the center of the footer
- Front page tests
- [ ] Body - "MAKE YOUR VOICE HEARD" is displayed at the top of the main body
- [ ] Body - Site is not empty below the MAKE YOUR VOICE HEARD header. (This content may change so it should be sufficient to just make sure it's not empty.
- [ ] Body - Extras div is displayed directly above the footer component
- [ ] Body - extras__band exists on the front page
- [ ] Body - extras__tweets exists on the front page
- [ ] Body - Extras__band articles exists on the front page
- [ ] Body - extras__media exists on the front page
- Tests for a page matching /issue/:issueid
- [x] Overall - Click on the first issue in the sidebar and execute 
- [ ] Overall - All header, sidebar, and footer tests should pass on this page
- [x] Body - Extras div is not displayed on an issue page
- [x] Body - call__header exists on the page 
- [x] Body - call__title exists within the call_header component
- [x] Body - call__reason exists within the call_header component below the call__title component
- [x] Body -  call__contact exists in the body positioned below the call__header component
- [x] Body - call__contact contains the following components: call__contact__image, call__contact__type, call__contact__name, call__contact__phone, call__contact__reason__header, and call__contact__reason
- [x] Body - call__script exists on the page
- [x] Body - call__script header exists within the call__script component and reads "Your script"
- [x] Body - call__script_body exists within the call__script component and beneath the call__script__header
- [ ] Body - component with attribute 'numberContactsLeft' should exist
- [x] Body - call__outcomes div should exist with components call__outcomes__header and call__outcomes__items
- [x] Body - text in call__outcomes__header should read "Enter your call result to get the next call:"
- [x] Body - call__outcomes__items should contain four buttons labeled 'UNAVAILABLE', 'LEFT VOICEMAIL', 'MADE CONTACT', and 'SKIP
- [ ] Body - If numberContactsLeft > call__contacts__left  should exist in the body with text that contains the value of numberContactsLeft

**Comment by nabrahamson** [comment]
Some notes for the readme:
You may run specific tests by running testcafe with the -t or -T option
-t <full test name>
-T <partial test name, must meet grep search criteria. Ex. Tests that start with donate may be found with "Donate.*>

Tests may be run in debug mode with the --inspect-brk option. 
```
testcafe --inspect-brk chrome web-tests/test.ts 
```
Breakpoints may be put in the test with the following syntax
```
// tslint:disable-next-line:no-debugger
debugger;
```
Then in chrome, navigate to `chrome://inspect`
On this page, under Remote Target there will be an inspect link, click to start the debugger.

**Comment by nabrahamson** [comment]
Because we will be testing local link pages, I don't believe it's necessary to check if each link on localhost work.

**Review by nickoneill — APPROVED** [review]

**Pull request merged**
