### PR TITLE
Default to browser geolocation

### PR DESCRIPTION
**Pull request by nickoneill**
PR from @capndesign's work, updating for the new design

### CODE REVIEW

**Comment by nickoneill** [comment]
@capndesign check this out on the new design, but it feels pretty 👍 to me as-is

**Comment by capndesign** [comment]
Passing this back to you, @nickoneill. It would be helpful to get normalized address data repeated back by our API. I’d like to show the user’s city after the browser finds them.

**Comment by nickoneill** [comment]
This is returned as `normalizedInput` on the response object now.

**Comment by capndesign** [comment]
Okay @nickoneill, I think this is ready. Review and merge if it looks good to you too!

**Comment by nickoneill** [comment]
Awesome, deploying now!

**Pull request merged**
